### ISSUE TITLE
Website Redesign & Rebuild

### ISSUE THREAD

**Issue by danekolsen** [codeforsanjose/codeforsanjose.github.io#41]
Since many people are experiencing dependency issues while trying to spin up local copies of the current project, and the site looks a little dated, we've been looking at a redesign and rebuild using either vanilla HTML/CSS/JS or maybe React/Gatsby. 

This issue serves as a start point for the redesign process.

**Comment by Kyle-Falconer** [comment]
I would recommend against a rewrite. If people are having difficulties with dependencies, then update the project structure to bring it closer to the official or recommended style for GitHub Pages.

What I've learned is that with the CFSJ website, longevity and simplicity is best. The pages need to be editable by people not familiar with website development and the project should ideally be hosted on GitHub Pages or Netlify.

There have been initiatives in the past with lofty goals of redesign and they have all failed because they became too complex or tried to reinvent a content management system.

**Comment by ychoy** [comment]
Thanks @danekolsen for completing this!
