### ISSUE TITLE
Silicon Valley Strong Listed Twice on Projects Page

### ISSUE THREAD

**Issue by sunnymui** [codeforsanjose/codeforsanjose.github.io#73]
Silicon Valley Strong is listed 2 times on the Projects page.

It should only be listed once.

**Comment by ErikaVasNormandy** [comment]
https://apply.codeforsanjose.org/projects/silicon-valley-strong

https://apply.codeforsanjose.org/projects/silicon-valley-strong-2

Checking in with the team to confirm if this project has been complete or not. We ought to list this project as completed on the site and combine them if they are referring to the same thing since 

I have unpublished the page though so that only https://apply.codeforsanjose.org/projects/silicon-valley-strong-2 is listed
