### ISSUE TITLE
Code of Conduct page missing

### ISSUE THREAD

**Issue by sunnymui** [codeforsanjose/codeforsanjose.github.io#75]
Anytime we link out to the code of conduct page on the codeforsanjose.org website, it's a broken link

That's because there is no codeofconduct.html file in the repo.

We need to add one.

How to Replicate:

1. Got to [http://www.codeforsanjose.com/codeofconduct.html](http://www.codeforsanjose.com/codeofconduct.html)
2. You are redirected due to page missing
3. Check the code for san jose website repo
4. Observe: no codeofconduct.html file

**Comment by ErikaVasNormandy** [comment]
I think we need to write a code of conduct, I did a bit of trawling but could not find anything even when just looking on a search engine

**Comment by ErikaVasNormandy** [comment]
Actually, we do have one
https://web.archive.org/web/20180203204230/http://www.codeforsanjose.com:80/codeofconduct.html

I say we could probably just copy and paste this, provided that we don't feel the need to add on anything new but I am open to suggestions. Otherwise, I feel that it is alright as it is

**Comment by sunnymui** [comment]
Maybe open a PR with the code of conduct text so we can do an open code
review on the text?

I dunno I'm just trying to be process oriented lol

**Comment by ErikaVasNormandy** [comment]
Sounds good, well since this has functionally been closed, we'll post it up on the leadership chat in Slack if people had any strong feelings about rewriting/reviewing the code of conduct
